# Generated by Django 5.2.7 on 2025-11-13 05:37

import django.core.validators
import services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), services.validators.validate_image_size, services.validators.validate_image_with_pillow], verbose_name='Аватар'),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
