# Generated by Django 5.2.7 on 2025-11-04 07:17

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(validators=[movies.models.validation_year], verbose_name='Год выхода'),
        ),
    ]
