# Generated by Django 5.2.7 on 2025-11-04 15:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from=['first_name', 'last_name'], unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', unique=True),
        ),
    ]
