# Generated by Django 5.2.7 on 2025-11-04 15:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_director_slug_alter_genre_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from=('first_name', 'last_name'), unique=True),
        ),
    ]
