# Generated by Django 5.2.7 on 2025-11-04 15:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_director_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='last_name', unique_with=('first_name',)),
        ),
    ]
