# Generated by Django 5.2.7 on 2025-11-05 07:19

import django.core.validators
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_director_slug'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='movies/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-rating'], name='movie_rating_36abf9_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['year'], name='movie_year_438d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre'], name='movie_genre_i_f00904_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['director'], name='movie_directo_e45394_idx'),
        ),
    ]
