# Generated by Django 5.2.7 on 2025-11-05 14:25

import django.core.validators
import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_tags_alter_movie_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movie_rating_36abf9_idx',
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='movies/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), movies.models.validate_image_size, movies.models.validate_image_with_pillow], verbose_name='Изображение'),
        ),
    ]
